### PR TITLE
Make font dark mode-compatible

### PR DESCRIPTION
**Pull request by MarloSM**
My OctoPrint theme is dark so it uses white font. This change will make it use the typical body colour.

Tp link smartplug font change

### CODE REVIEW

**Comment by jneilliii** [comment]
What Theme are you using, as I don't see the same thing in mine?

image

Also, if you don't mind rebasing on rc branch?

**Comment by MarloSM** [comment]
I'm using Discorded. It doesn't affect the title, only the body. Here's how it looked before.

image

**Comment by jneilliii** [comment]
Oh, thanks for the clarification. I forgot I keep my panel minimized and never look at the power data...lol.

**Comment by jneilliii** [comment]
I went ahead and made the change to the rc branch directly.

**Pull request closed without merging**
